[workspace]
members = [
    "src/backend/chainkey_testing_canister",
    "src/backend/chronolock_canister",
    "src/backend/crnl_ledger_canister",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
